[build]
  command = "echo Hi!"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
    default-src 'none';
    script-src 'self' https://www.findberry.com https://hypothes.is https://code.jquery.com https://cdn.hypothes.is https://cdnjs.cloudflare.com https://stackpath.bootstrapcdn.com https://outsidecto.disqus.com https://outsidectodev.disqus.com https://c.disquscdn.com;
    style-src 'self' https://stackpath.bootstrapcdn.com https://fonts.googleapis.com https://www.findberry.com https://cdn.hypothes.is  https://c.disquscdn.com;
    font-src https://fonts.googleapis.com https://fonts.gstatic.com/;
    frame-src https://hypothes.is https://disqus.com https://www.findberry.com;
    connect-src 'self' https://links.services.disqus.com;
    img-src 'self';
    form-action 'self';
    """
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self)"
[[plugins]]
  package = "@netlify/plugin-csp-nonce"
